package com.example.a01_compose_study.domain.model

sealed class ScreenType {
    object None : ScreenType()
    object ContentScreen : ScreenType()
    object ServiceScreen : ScreenType()
    object Ptt : ScreenType()
    object Notice : ScreenType()
    object List : ScreenType()
    object YesNo : ScreenType()
    object Navigation : ScreenType()
    object NavigationNotice : ScreenType()
    object LocalSearch : ScreenType()
    object Favorite : ScreenType()
    object FavoriteConfirm : ScreenType()
    object FavoriteSearchConfirm : ScreenType()
    object NaviWaypoint : ScreenType()
    object Radio : ScreenType()
    object RadioList : ScreenType()
    object Weather : ScreenType()
    object WeatherList : ScreenType()
    object MessageName : ScreenType()
    object MessageChange : ScreenType()
    object HelpList : ScreenType()
    object HelpDetailList : ScreenType()
    object SmallText : ScreenType()
    object MediumText : ScreenType()
    object LargeText : ScreenType()
}
